version: '3.9'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: todolists
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    healthcheck:
      test: psql -U postgres -c '\l'
      interval: 1s
      timeout: 10s
      retries: 5